// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: forumline/hub/v1/hub.proto

package hubv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterForumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterForumRequest) Reset() {
	*x = RegisterForumRequest{}
	mi := &file_forumline_hub_v1_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterForumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterForumRequest) ProtoMessage() {}

func (x *RegisterForumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forumline_hub_v1_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterForumRequest.ProtoReflect.Descriptor instead.
func (*RegisterForumRequest) Descriptor() ([]byte, []int) {
	return file_forumline_hub_v1_hub_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterForumRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RegisterForumRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterForumRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterForumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterForumResponse) Reset() {
	*x = RegisterForumResponse{}
	mi := &file_forumline_hub_v1_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterForumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterForumResponse) ProtoMessage() {}

func (x *RegisterForumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forumline_hub_v1_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterForumResponse.ProtoReflect.Descriptor instead.
func (*RegisterForumResponse) Descriptor() ([]byte, []int) {
	return file_forumline_hub_v1_hub_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterForumResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

var File_forumline_hub_v1_hub_proto protoreflect.FileDescriptor

const file_forumline_hub_v1_hub_proto_rawDesc = "" +
	"\n" +
	"\x1aforumline/hub/v1/hub.proto\x12\x10forumline.hub.v1\"f\n" +
	"\x14RegisterForumRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"1\n" +
	"\x15RegisterForumResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated2n\n" +
	"\n" +
	"HubService\x12`\n" +
	"\rRegisterForum\x12&.forumline.hub.v1.RegisterForumRequest\x1a'.forumline.hub.v1.RegisterForumResponseB;Z9github.com/forumline/forumline/rpc/forumline/hub/v1;hubv1b\x06proto3"

var (
	file_forumline_hub_v1_hub_proto_rawDescOnce sync.Once
	file_forumline_hub_v1_hub_proto_rawDescData []byte
)

func file_forumline_hub_v1_hub_proto_rawDescGZIP() []byte {
	file_forumline_hub_v1_hub_proto_rawDescOnce.Do(func() {
		file_forumline_hub_v1_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forumline_hub_v1_hub_proto_rawDesc), len(file_forumline_hub_v1_hub_proto_rawDesc)))
	})
	return file_forumline_hub_v1_hub_proto_rawDescData
}

var file_forumline_hub_v1_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_forumline_hub_v1_hub_proto_goTypes = []any{
	(*RegisterForumRequest)(nil),  // 0: forumline.hub.v1.RegisterForumRequest
	(*RegisterForumResponse)(nil), // 1: forumline.hub.v1.RegisterForumResponse
}
var file_forumline_hub_v1_hub_proto_depIdxs = []int32{
	0, // 0: forumline.hub.v1.HubService.RegisterForum:input_type -> forumline.hub.v1.RegisterForumRequest
	1, // 1: forumline.hub.v1.HubService.RegisterForum:output_type -> forumline.hub.v1.RegisterForumResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_forumline_hub_v1_hub_proto_init() }
func file_forumline_hub_v1_hub_proto_init() {
	if File_forumline_hub_v1_hub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forumline_hub_v1_hub_proto_rawDesc), len(file_forumline_hub_v1_hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forumline_hub_v1_hub_proto_goTypes,
		DependencyIndexes: file_forumline_hub_v1_hub_proto_depIdxs,
		MessageInfos:      file_forumline_hub_v1_hub_proto_msgTypes,
	}.Build()
	File_forumline_hub_v1_hub_proto = out.File
	file_forumline_hub_v1_hub_proto_goTypes = nil
	file_forumline_hub_v1_hub_proto_depIdxs = nil
}
