// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: forumline/platform/v1/platform.proto

package platformv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/forumline/forumline/rpc/forumline/platform/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PlatformServiceName is the fully-qualified name of the PlatformService service.
	PlatformServiceName = "forumline.platform.v1.PlatformService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PlatformServiceProvisionForumProcedure is the fully-qualified name of the PlatformService's
	// ProvisionForum RPC.
	PlatformServiceProvisionForumProcedure = "/forumline.platform.v1.PlatformService/ProvisionForum"
)

// PlatformServiceClient is a client for the forumline.platform.v1.PlatformService service.
type PlatformServiceClient interface {
	ProvisionForum(context.Context, *connect.Request[v1.ProvisionForumRequest]) (*connect.Response[v1.ProvisionForumResponse], error)
}

// NewPlatformServiceClient constructs a client for the forumline.platform.v1.PlatformService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPlatformServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PlatformServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	platformServiceMethods := v1.File_forumline_platform_v1_platform_proto.Services().ByName("PlatformService").Methods()
	return &platformServiceClient{
		provisionForum: connect.NewClient[v1.ProvisionForumRequest, v1.ProvisionForumResponse](
			httpClient,
			baseURL+PlatformServiceProvisionForumProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ProvisionForum")),
			connect.WithClientOptions(opts...),
		),
	}
}

// platformServiceClient implements PlatformServiceClient.
type platformServiceClient struct {
	provisionForum *connect.Client[v1.ProvisionForumRequest, v1.ProvisionForumResponse]
}

// ProvisionForum calls forumline.platform.v1.PlatformService.ProvisionForum.
func (c *platformServiceClient) ProvisionForum(ctx context.Context, req *connect.Request[v1.ProvisionForumRequest]) (*connect.Response[v1.ProvisionForumResponse], error) {
	return c.provisionForum.CallUnary(ctx, req)
}

// PlatformServiceHandler is an implementation of the forumline.platform.v1.PlatformService service.
type PlatformServiceHandler interface {
	ProvisionForum(context.Context, *connect.Request[v1.ProvisionForumRequest]) (*connect.Response[v1.ProvisionForumResponse], error)
}

// NewPlatformServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPlatformServiceHandler(svc PlatformServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	platformServiceMethods := v1.File_forumline_platform_v1_platform_proto.Services().ByName("PlatformService").Methods()
	platformServiceProvisionForumHandler := connect.NewUnaryHandler(
		PlatformServiceProvisionForumProcedure,
		svc.ProvisionForum,
		connect.WithSchema(platformServiceMethods.ByName("ProvisionForum")),
		connect.WithHandlerOptions(opts...),
	)
	return "/forumline.platform.v1.PlatformService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PlatformServiceProvisionForumProcedure:
			platformServiceProvisionForumHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPlatformServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPlatformServiceHandler struct{}

func (UnimplementedPlatformServiceHandler) ProvisionForum(context.Context, *connect.Request[v1.ProvisionForumRequest]) (*connect.Response[v1.ProvisionForumResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("forumline.platform.v1.PlatformService.ProvisionForum is not implemented"))
}
