// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: forumline/platform/v1/platform.proto

package platformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProvisionForumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionForumRequest) Reset() {
	*x = ProvisionForumRequest{}
	mi := &file_forumline_platform_v1_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionForumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionForumRequest) ProtoMessage() {}

func (x *ProvisionForumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forumline_platform_v1_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionForumRequest.ProtoReflect.Descriptor instead.
func (*ProvisionForumRequest) Descriptor() ([]byte, []int) {
	return file_forumline_platform_v1_platform_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionForumRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProvisionForumRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProvisionForumRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProvisionForumRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ProvisionForumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SchemaName    string                 `protobuf:"bytes,4,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionForumResponse) Reset() {
	*x = ProvisionForumResponse{}
	mi := &file_forumline_platform_v1_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionForumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionForumResponse) ProtoMessage() {}

func (x *ProvisionForumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forumline_platform_v1_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionForumResponse.ProtoReflect.Descriptor instead.
func (*ProvisionForumResponse) Descriptor() ([]byte, []int) {
	return file_forumline_platform_v1_platform_proto_rawDescGZIP(), []int{1}
}

func (x *ProvisionForumResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ProvisionForumResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProvisionForumResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProvisionForumResponse) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

var File_forumline_platform_v1_platform_proto protoreflect.FileDescriptor

const file_forumline_platform_v1_platform_proto_rawDesc = "" +
	"\n" +
	"$forumline/platform/v1/platform.proto\x12\x15forumline.platform.v1\"z\n" +
	"\x15ProvisionForumRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"y\n" +
	"\x16ProvisionForumResponse\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vschema_name\x18\x04 \x01(\tR\n" +
	"schemaName2\x80\x01\n" +
	"\x0fPlatformService\x12m\n" +
	"\x0eProvisionForum\x12,.forumline.platform.v1.ProvisionForumRequest\x1a-.forumline.platform.v1.ProvisionForumResponseBEZCgithub.com/forumline/forumline/rpc/forumline/platform/v1;platformv1b\x06proto3"

var (
	file_forumline_platform_v1_platform_proto_rawDescOnce sync.Once
	file_forumline_platform_v1_platform_proto_rawDescData []byte
)

func file_forumline_platform_v1_platform_proto_rawDescGZIP() []byte {
	file_forumline_platform_v1_platform_proto_rawDescOnce.Do(func() {
		file_forumline_platform_v1_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forumline_platform_v1_platform_proto_rawDesc), len(file_forumline_platform_v1_platform_proto_rawDesc)))
	})
	return file_forumline_platform_v1_platform_proto_rawDescData
}

var file_forumline_platform_v1_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_forumline_platform_v1_platform_proto_goTypes = []any{
	(*ProvisionForumRequest)(nil),  // 0: forumline.platform.v1.ProvisionForumRequest
	(*ProvisionForumResponse)(nil), // 1: forumline.platform.v1.ProvisionForumResponse
}
var file_forumline_platform_v1_platform_proto_depIdxs = []int32{
	0, // 0: forumline.platform.v1.PlatformService.ProvisionForum:input_type -> forumline.platform.v1.ProvisionForumRequest
	1, // 1: forumline.platform.v1.PlatformService.ProvisionForum:output_type -> forumline.platform.v1.ProvisionForumResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_forumline_platform_v1_platform_proto_init() }
func file_forumline_platform_v1_platform_proto_init() {
	if File_forumline_platform_v1_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forumline_platform_v1_platform_proto_rawDesc), len(file_forumline_platform_v1_platform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forumline_platform_v1_platform_proto_goTypes,
		DependencyIndexes: file_forumline_platform_v1_platform_proto_depIdxs,
		MessageInfos:      file_forumline_platform_v1_platform_proto_msgTypes,
	}.Build()
	File_forumline_platform_v1_platform_proto = out.File
	file_forumline_platform_v1_platform_proto_goTypes = nil
	file_forumline_platform_v1_platform_proto_depIdxs = nil
}
