// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type ForumlineForum struct {
	ID                  uuid.UUID  `json:"id"`
	Domain              string     `json:"domain"`
	Name                string     `json:"name"`
	IconUrl             *string    `json:"icon_url"`
	ApiBase             string     `json:"api_base"`
	WebBase             string     `json:"web_base"`
	Capabilities        []string   `json:"capabilities"`
	Description         *string    `json:"description"`
	OwnerID             *string    `json:"owner_id"`
	Approved            bool       `json:"approved"`
	ScreenshotUrl       *string    `json:"screenshot_url"`
	Tags                []string   `json:"tags"`
	MemberCount         int32      `json:"member_count"`
	LastSeenAt          *time.Time `json:"last_seen_at"`
	ConsecutiveFailures int32      `json:"consecutive_failures"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
}

type ForumlineMembership struct {
	ID                 uuid.UUID  `json:"id"`
	UserID             string     `json:"user_id"`
	ForumID            uuid.UUID  `json:"forum_id"`
	JoinedAt           time.Time  `json:"joined_at"`
	NotificationsMuted bool       `json:"notifications_muted"`
	ForumAuthedAt      *time.Time `json:"forum_authed_at"`
}

type ForumlineProfile struct {
	ID               string    `json:"id"`
	Username         string    `json:"username"`
	DisplayName      string    `json:"display_name"`
	AvatarUrl        *string   `json:"avatar_url"`
	Bio              *string   `json:"bio"`
	StatusMessage    string    `json:"status_message"`
	OnlineStatus     string    `json:"online_status"`
	ShowOnlineStatus bool      `json:"show_online_status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}
