// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const countExistingUsers = `-- name: CountExistingUsers :one
SELECT count(*) FROM forumline_profiles WHERE id = ANY($1::text[])
`

func (q *Queries) CountExistingUsers(ctx context.Context, dollar_1 []string) (int64, error) {
	row := q.db.QueryRow(ctx, countExistingUsers, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fetchProfilesByIDs = `-- name: FetchProfilesByIDs :many
SELECT id, username, display_name, avatar_url
FROM forumline_profiles WHERE id = ANY($1::text[])
`

type FetchProfilesByIDsRow struct {
	ID          string  `json:"id"`
	Username    string  `json:"username"`
	DisplayName string  `json:"display_name"`
	AvatarUrl   *string `json:"avatar_url"`
}

func (q *Queries) FetchProfilesByIDs(ctx context.Context, dollar_1 []string) ([]FetchProfilesByIDsRow, error) {
	rows, err := q.db.Query(ctx, fetchProfilesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchProfilesByIDsRow{}
	for rows.Next() {
		var i FetchProfilesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getForumIDByDomain = `-- name: GetForumIDByDomain :one
SELECT id FROM forumline_forums WHERE domain = $1
`

func (q *Queries) GetForumIDByDomain(ctx context.Context, domain string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getForumIDByDomain, domain)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getForumNameByDomain = `-- name: GetForumNameByDomain :one
SELECT name FROM forumline_forums WHERE domain = $1
`

func (q *Queries) GetForumNameByDomain(ctx context.Context, domain string) (string, error) {
	row := q.db.QueryRow(ctx, getForumNameByDomain, domain)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getOnlineStatusPreferences = `-- name: GetOnlineStatusPreferences :many
SELECT id, online_status, show_online_status
FROM forumline_profiles WHERE id = ANY($1::text[])
`

type GetOnlineStatusPreferencesRow struct {
	ID               string `json:"id"`
	OnlineStatus     string `json:"online_status"`
	ShowOnlineStatus bool   `json:"show_online_status"`
}

func (q *Queries) GetOnlineStatusPreferences(ctx context.Context, dollar_1 []string) ([]GetOnlineStatusPreferencesRow, error) {
	rows, err := q.db.Query(ctx, getOnlineStatusPreferences, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOnlineStatusPreferencesRow{}
	for rows.Next() {
		var i GetOnlineStatusPreferencesRow
		if err := rows.Scan(&i.ID, &i.OnlineStatus, &i.ShowOnlineStatus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfile = `-- name: GetProfile :one

SELECT id, username, display_name, avatar_url, bio, status_message, online_status, show_online_status
FROM forumline_profiles WHERE id = $1
`

type GetProfileRow struct {
	ID               string  `json:"id"`
	Username         string  `json:"username"`
	DisplayName      string  `json:"display_name"`
	AvatarUrl        *string `json:"avatar_url"`
	Bio              *string `json:"bio"`
	StatusMessage    string  `json:"status_message"`
	OnlineStatus     string  `json:"online_status"`
	ShowOnlineStatus bool    `json:"show_online_status"`
}

// READ-ONLY: profiles are owned by the hub service.
func (q *Queries) GetProfile(ctx context.Context, id string) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i GetProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.StatusMessage,
		&i.OnlineStatus,
		&i.ShowOnlineStatus,
	)
	return i, err
}

const getSenderUsername = `-- name: GetSenderUsername :one
SELECT username FROM forumline_profiles WHERE id = $1
`

func (q *Queries) GetSenderUsername(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getSenderUsername, id)
	var username string
	err := row.Scan(&username)
	return username, err
}

const isNotificationsMuted = `-- name: IsNotificationsMuted :one
SELECT notifications_muted FROM forumline_memberships WHERE user_id = $1 AND forum_id = $2
`

type IsNotificationsMutedParams struct {
	UserID  string    `json:"user_id"`
	ForumID uuid.UUID `json:"forum_id"`
}

func (q *Queries) IsNotificationsMuted(ctx context.Context, arg IsNotificationsMutedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isNotificationsMuted, arg.UserID, arg.ForumID)
	var notifications_muted bool
	err := row.Scan(&notifications_muted)
	return notifications_muted, err
}

const isNotificationsMutedByDomain = `-- name: IsNotificationsMutedByDomain :one
SELECT m.notifications_muted
FROM forumline_memberships m
JOIN forumline_forums f ON f.id = m.forum_id
WHERE m.user_id = $1 AND f.domain = $2
`

type IsNotificationsMutedByDomainParams struct {
	UserID string `json:"user_id"`
	Domain string `json:"domain"`
}

func (q *Queries) IsNotificationsMutedByDomain(ctx context.Context, arg IsNotificationsMutedByDomainParams) (bool, error) {
	row := q.db.QueryRow(ctx, isNotificationsMutedByDomain, arg.UserID, arg.Domain)
	var notifications_muted bool
	err := row.Scan(&notifications_muted)
	return notifications_muted, err
}

const profileExists = `-- name: ProfileExists :one
SELECT EXISTS(SELECT 1 FROM forumline_profiles WHERE id = $1)
`

func (q *Queries) ProfileExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, profileExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const searchProfiles = `-- name: SearchProfiles :many
SELECT id, username, display_name, avatar_url
FROM forumline_profiles
WHERE id != $1 AND (username ILIKE $2 OR display_name ILIKE $2)
LIMIT 10
`

type SearchProfilesParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type SearchProfilesRow struct {
	ID          string  `json:"id"`
	Username    string  `json:"username"`
	DisplayName string  `json:"display_name"`
	AvatarUrl   *string `json:"avatar_url"`
}

func (q *Queries) SearchProfiles(ctx context.Context, arg SearchProfilesParams) ([]SearchProfilesRow, error) {
	rows, err := q.db.Query(ctx, searchProfiles, arg.ID, arg.Username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProfilesRow{}
	for rows.Next() {
		var i SearchProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
