// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: forumline/hub/v1/hub.proto

package hubv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/forumline/forumline/rpc/forumline/hub/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HubServiceName is the fully-qualified name of the HubService service.
	HubServiceName = "forumline.hub.v1.HubService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HubServiceRegisterForumProcedure is the fully-qualified name of the HubService's RegisterForum
	// RPC.
	HubServiceRegisterForumProcedure = "/forumline.hub.v1.HubService/RegisterForum"
)

// HubServiceClient is a client for the forumline.hub.v1.HubService service.
type HubServiceClient interface {
	RegisterForum(context.Context, *connect.Request[v1.RegisterForumRequest]) (*connect.Response[v1.RegisterForumResponse], error)
}

// NewHubServiceClient constructs a client for the forumline.hub.v1.HubService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHubServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HubServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	hubServiceMethods := v1.File_forumline_hub_v1_hub_proto.Services().ByName("HubService").Methods()
	return &hubServiceClient{
		registerForum: connect.NewClient[v1.RegisterForumRequest, v1.RegisterForumResponse](
			httpClient,
			baseURL+HubServiceRegisterForumProcedure,
			connect.WithSchema(hubServiceMethods.ByName("RegisterForum")),
			connect.WithClientOptions(opts...),
		),
	}
}

// hubServiceClient implements HubServiceClient.
type hubServiceClient struct {
	registerForum *connect.Client[v1.RegisterForumRequest, v1.RegisterForumResponse]
}

// RegisterForum calls forumline.hub.v1.HubService.RegisterForum.
func (c *hubServiceClient) RegisterForum(ctx context.Context, req *connect.Request[v1.RegisterForumRequest]) (*connect.Response[v1.RegisterForumResponse], error) {
	return c.registerForum.CallUnary(ctx, req)
}

// HubServiceHandler is an implementation of the forumline.hub.v1.HubService service.
type HubServiceHandler interface {
	RegisterForum(context.Context, *connect.Request[v1.RegisterForumRequest]) (*connect.Response[v1.RegisterForumResponse], error)
}

// NewHubServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHubServiceHandler(svc HubServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	hubServiceMethods := v1.File_forumline_hub_v1_hub_proto.Services().ByName("HubService").Methods()
	hubServiceRegisterForumHandler := connect.NewUnaryHandler(
		HubServiceRegisterForumProcedure,
		svc.RegisterForum,
		connect.WithSchema(hubServiceMethods.ByName("RegisterForum")),
		connect.WithHandlerOptions(opts...),
	)
	return "/forumline.hub.v1.HubService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HubServiceRegisterForumProcedure:
			hubServiceRegisterForumHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHubServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHubServiceHandler struct{}

func (UnimplementedHubServiceHandler) RegisterForum(context.Context, *connect.Request[v1.RegisterForumRequest]) (*connect.Response[v1.RegisterForumResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("forumline.hub.v1.HubService.RegisterForum is not implemented"))
}
