/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/forumline/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start login flow
         * @description Redirects the user to the identity provider's authorization endpoint to begin
         *     the OAuth/OIDC login flow. After authentication the provider redirects back to
         *     the callback endpoint.
         */
        get: operations["startLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forumline/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth callback
         * @description Handles the OAuth/OIDC callback from the identity provider. Validates the state
         *     parameter, exchanges the authorization code for tokens, creates or links the local
         *     forum profile, sets a session cookie, and redirects the user back to the forum.
         */
        get: operations["authCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forumline/auth/token-exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange JWT for session (iframe flow)
         * @description Validates a JWT sent via `postMessage` from an embedding app (the "invisible handshake"
         *     for iframe-based browsing). Returns user info and a local session without a redirect flow.
         *     If the forum is not embedded in an app, may return `501 Not Implemented`.
         */
        post: operations["tokenExchange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forumline/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current session
         * @description Returns the current session info from cookies. If the user is not logged in,
         *     returns `null` or an empty session object.
         */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /**
         * Log out
         * @description Clears the session cookie and returns success.
         */
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get forum configuration
         * @description Returns the forum's public configuration used by the frontend for discovery
         *     and initialization. Includes the forum name, hosted mode flag, icon URL, and
         *     optionally the LiveKit server URL.
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all categories
         * @description Returns all forum categories ordered by `sort_order`.
         */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get category by slug
         * @description Returns a single category by its URL slug.
         */
        get: operations["getCategoryBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all chat channels
         * @description Returns all chat channels.
         */
        get: operations["listChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/forumline-manifest.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forumline discovery manifest
         * @description Returns the Forumline manifest for forum discovery. Other services in the Forumline
         *     network use this to discover a forum's capabilities, API base URL, and identity.
         */
        get: operations["getManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List threads
         * @description Returns threads ordered by pinned status and last post time (most recent first).
         *     Supports pagination via a `limit` query parameter.
         */
        get: operations["listThreads"];
        put?: never;
        /**
         * Create a thread
         * @description Creates a new forum thread. Requires authentication.
         */
        post: operations["createThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get thread by ID
         * @description Returns a single thread with its embedded author and category.
         */
        get: operations["getThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a thread
         * @description Updates a thread's fields. Only the thread author or a forum admin can update a thread.
         *     All fields are optional — only provided fields are updated.
         */
        patch: operations["updateThread"];
        trace?: never;
    };
    "/api/categories/{slug}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List threads by category
         * @description Returns all threads in a given category, identified by slug.
         */
        get: operations["listThreadsByCategory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List threads by user
         * @description Returns all threads authored by the specified user.
         */
        get: operations["listUserThreads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search threads
         * @description Searches threads by title using case-insensitive LIKE matching.
         */
        get: operations["searchThreads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{id}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List posts in a thread
         * @description Returns all posts in a thread, ordered by creation time.
         */
        get: operations["listPostsByThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream new posts (SSE)
         * @description Server-Sent Events stream for realtime new posts in a thread. Each event contains
         *     a post object enriched with the author profile. Sends `:connected` on open and
         *     `:heartbeat` every 30 seconds.
         */
        get: operations["streamPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a post
         * @description Creates a new post in a thread. Automatically updates the thread's post count and
         *     `last_post_at` timestamp, and triggers notifications for thread participants.
         */
        post: operations["createPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List posts by user
         * @description Returns all posts authored by the specified user.
         */
        get: operations["listUserPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search posts
         * @description Searches posts by content using case-insensitive LIKE matching.
         */
        get: operations["searchPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{slug}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List chat messages
         * @description Returns recent chat messages for a channel, identified by slug.
         */
        get: operations["listChatMessages"];
        put?: never;
        /**
         * Send a chat message
         * @description Sends a message to a chat channel identified by slug.
         */
        post: operations["sendChatMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/_by-id/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a chat message by channel ID
         * @description Sends a message to a chat channel identified by its UUID.
         */
        post: operations["sendChatMessageByID"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{slug}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream chat messages (SSE)
         * @description Server-Sent Events stream for realtime chat messages in a channel. Each event
         *     contains a chat message object enriched with the author profile. Sends `:connected`
         *     on open and `:heartbeat` every 30 seconds.
         */
        get: operations["streamChatMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get profile by ID
         * @description Returns a user profile by its UUID.
         */
        get: operations["getProfile"];
        /**
         * Create or update profile
         * @description Creates or updates the user's own profile. The path `{id}` must match the
         *     authenticated user's ID. All fields are optional for partial updates; if
         *     `username` is provided the full profile is upserted.
         */
        put: operations["upsertProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/by-username/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get profile by username
         * @description Returns a user profile by its unique username.
         */
        get: operations["getProfileByUsername"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get profiles in batch
         * @description Returns multiple profiles by their IDs. Pass a comma-separated list of UUIDs.
         *     Returns an empty array if no IDs are provided.
         */
        get: operations["getProfilesBatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}/forumline-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Forumline ID link
         * @description Removes the `forumline_id` association from the user's profile. The path `{id}` must
         *     match the authenticated user's ID. This disconnects the local forum profile from the
         *     Forumline network identity.
         */
        delete: operations["clearForumlineId"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bookmarks
         * @description Returns all bookmarked threads for the authenticated user.
         */
        get: operations["listBookmarks"];
        put?: never;
        /**
         * Bookmark a thread
         * @description Adds a thread to the authenticated user's bookmarks.
         */
        post: operations["addBookmark"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks/{threadId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check bookmark status
         * @description Checks whether a specific thread is bookmarked by the authenticated user.
         *     Returns `bookmarked: true` with the bookmark `id` if it exists, or `bookmarked: false`.
         */
        get: operations["getBookmarkStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks/{threadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove bookmark by thread ID
         * @description Removes a thread from the authenticated user's bookmarks.
         */
        delete: operations["removeBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks/by-id/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove bookmark by bookmark ID
         * @description Removes a bookmark by its own UUID.
         */
        delete: operations["removeBookmarkById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channel-follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List followed categories
         * @description Returns the list of category IDs the authenticated user follows.
         */
        get: operations["listChannelFollows"];
        put?: never;
        /**
         * Follow a category
         * @description Subscribes the authenticated user to notifications for a category.
         */
        post: operations["followChannel"];
        /**
         * Unfollow a category
         * @description Unsubscribes the authenticated user from notifications for a category.
         */
        delete: operations["unfollowChannel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List notifications
         * @description Returns the 20 most recent notifications for the authenticated user.
         */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark all notifications as read
         * @description Marks all notifications for the authenticated user as read.
         */
        post: operations["markAllNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forumline/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Forumline-format notifications
         * @description Returns the 50 most recent notifications in Forumline protocol format (with `forum_domain`,
         *     `body` instead of `message`, `timestamp` instead of `created_at`). Used by the Forumline
         *     app to aggregate notifications across forums.
         */
        get: operations["listForumlineNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forumline/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a notification as read
         * @description Marks a single notification as read by its ID.
         */
        post: operations["markNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forumline/unread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get unread counts
         * @description Returns unread notification, chat mention, and DM counts for the authenticated user.
         */
        get: operations["getUnreadCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forumline/notifications/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream notifications (SSE)
         * @description Server-Sent Events stream for realtime notifications. Events are in Forumline protocol
         *     format (with `forum_domain`, `body`, `timestamp`). Sends `:connected` on open and
         *     `:heartbeat` every 30 seconds. Only delivers notifications belonging to the authenticated user.
         */
        get: operations["streamNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List notification preferences
         * @description Returns the authenticated user's notification preferences by category.
         */
        get: operations["listNotificationPreferences"];
        /**
         * Update a notification preference
         * @description Creates or updates a notification preference for a specific category.
         *     Valid categories: `reply`, `mention`, `chat_mention`, `dm`, `new_thread`.
         */
        put: operations["updateNotificationPreference"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice-rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List voice rooms
         * @description Returns all configured voice rooms.
         */
        get: operations["listVoiceRooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/livekit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List LiveKit participants
         * @description Lists participants in LiveKit voice rooms. If a `room` query parameter is provided,
         *     returns participants for that specific room. Otherwise returns a map of all rooms
         *     with their participant counts, names, and identities.
         */
        get: operations["getLiveKitParticipants"];
        put?: never;
        /**
         * Get LiveKit access token
         * @description Generates a LiveKit access token for joining a voice room. Before generating
         *     the token, removes the user from any existing rooms to enforce one-room-at-a-time.
         *     Returns `500` if LiveKit is not configured.
         */
        post: operations["getLiveKitToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice-presence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List voice presence
         * @description Returns all users currently in voice rooms with their profile data.
         */
        get: operations["listVoicePresence"];
        /**
         * Set voice presence
         * @description Records the authenticated user as present in a voice room.
         */
        put: operations["setVoicePresence"];
        post?: never;
        /**
         * Clear voice presence
         * @description Removes the authenticated user's voice presence from all rooms.
         */
        delete: operations["clearVoicePresence"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice-presence/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream voice presence changes (SSE)
         * @description Server-Sent Events stream for realtime voice presence changes (join, leave, update).
         *     Each event contains voice presence data enriched with the user's profile. Sends
         *     `:connected` on open and `:heartbeat` every 30 seconds.
         */
        get: operations["streamVoicePresence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/avatars/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload an avatar or image
         * @description Accepts a multipart file upload (max 5 MB, images only) and stores it via
         *     the configured FileStorage backend. The `path` field controls the storage key;
         *     if omitted it defaults to `user/{userId}/custom.png`. Users can only upload to
         *     their own `user/{id}/` prefix or to `thread/` paths.
         */
        post: operations["uploadAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get admin statistics
         * @description Returns dashboard statistics (total users, threads, posts). Requires admin privileges.
         */
        get: operations["getAdminStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all users (admin)
         * @description Returns up to 50 user profiles. Requires admin privileges.
         */
        get: operations["listAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import forum data
         * @description Imports forum data from a Forumline export file. The import is additive — it uses
         *     `ON CONFLICT DO NOTHING` to avoid duplicating data if run multiple times. Preserves
         *     original UUIDs and timestamps. Requires admin privileges.
         */
        post: operations["importData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Profile: {
            /** Format: uuid */
            id: string;
            username: string;
            display_name?: string | null;
            /** Format: uri */
            avatar_url?: string | null;
            bio?: string | null;
            /** Format: uri */
            website?: string | null;
            is_admin: boolean;
            /** @description Linked Forumline network user ID */
            forumline_id?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Category: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string | null;
            sort_order: number;
            /** Format: date-time */
            created_at: string;
        };
        Thread: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            category_id: string;
            /** Format: uuid */
            author_id: string;
            title: string;
            slug: string;
            /** @description Optional body/description for the thread */
            content?: string | null;
            /** Format: uri */
            image_url?: string | null;
            is_pinned: boolean;
            is_locked: boolean;
            view_count: number;
            post_count: number;
            /** Format: date-time */
            last_post_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            author: components["schemas"]["Profile"];
            category: components["schemas"]["Category"];
        };
        Post: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            thread_id: string;
            /** Format: uuid */
            author_id: string;
            content: string;
            /**
             * Format: uuid
             * @description ID of the post this is a reply to
             */
            reply_to_id?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            author: components["schemas"]["Profile"];
        };
        Channel: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        VoiceRoom: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** Format: date-time */
            created_at: string;
        };
        ChatMessage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            channel_id: string;
            /** Format: uuid */
            author_id: string;
            content: string;
            /** Format: date-time */
            created_at: string;
            author: components["schemas"]["Profile"];
        };
        VoicePresence: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            room_slug: string;
            /** Format: date-time */
            joined_at: string;
            profile: components["schemas"]["Profile"];
        };
        Bookmark: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            thread: components["schemas"]["Thread"];
        };
        Notification: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** @description Notification type (e.g. reply, mention, chat_mention, dm, new_thread) */
            type: string;
            title: string;
            message: string;
            link?: string | null;
            read: boolean;
            /** Format: date-time */
            created_at: string;
        };
        ForumlineNotification: {
            /** Format: uuid */
            id: string;
            type: string;
            title: string;
            body: string;
            link: string;
            read: boolean;
            /** Format: date-time */
            timestamp: string;
            /** @description Domain of the forum that generated this notification */
            forum_domain: string;
        };
        NotificationPreference: {
            /** @enum {string} */
            category: "reply" | "mention" | "chat_mention" | "dm" | "new_thread";
            enabled: boolean;
        };
        AdminStats: {
            totalUsers: number;
            totalThreads: number;
            totalPosts: number;
        };
        ForumConfig: {
            /** @description Forum display name */
            name: string;
            /** @description Whether this forum runs on the Forumline hosted platform */
            hosted_mode: boolean;
            /**
             * Format: uri
             * @description Forum icon/logo URL
             */
            icon_url?: string;
            /**
             * Format: uri
             * @description LiveKit server WebSocket URL (only present if voice is enabled)
             */
            livekit_url?: string;
        };
        ForumlineManifest: {
            /** @example 1 */
            forumline_version: string;
            name: string;
            domain: string;
            /** Format: uri */
            icon_url?: string;
            /**
             * Format: uri
             * @description Base URL for Forumline protocol API endpoints
             */
            api_base: string;
            /**
             * Format: uri
             * @description Base URL for the forum's web UI
             */
            web_base: string;
            capabilities: ("threads" | "chat" | "voice" | "notifications")[];
        };
        Session: {
            /** Format: uuid */
            user_id?: string;
            username?: string;
            display_name?: string;
            /** Format: uri */
            avatar_url?: string;
            is_admin?: boolean;
        };
        CreateThreadRequest: {
            /**
             * Format: uuid
             * @description Category to create the thread in
             */
            category_id: string;
            /** @description Thread title */
            title: string;
            /** @description URL-friendly slug for the thread */
            slug: string;
            /** @description Optional thread body/description */
            content?: string | null;
            /**
             * Format: uri
             * @description Optional header image URL
             */
            image_url?: string | null;
        };
        /** @description All fields are optional. Only provided fields are updated. */
        UpdateThreadRequest: {
            /** Format: uri */
            image_url?: string | null;
            /** Format: date-time */
            last_post_at?: string;
            post_count?: number;
            is_pinned?: boolean;
            is_locked?: boolean;
        };
        CreatePostRequest: {
            /**
             * Format: uuid
             * @description Thread to post in
             */
            thread_id: string;
            /** @description Post content (supports Markdown) */
            content: string;
            /**
             * Format: uuid
             * @description Optional ID of the post being replied to
             */
            reply_to_id?: string | null;
        };
        SendChatMessageRequest: {
            /** @description Message content */
            content: string;
        };
        /**
         * @description All fields are optional for partial updates. If `username` is provided, the full
         *     profile is upserted (create or replace).
         */
        UpsertProfileRequest: {
            username?: string;
            display_name?: string | null;
            /** Format: uri */
            avatar_url?: string | null;
            bio?: string | null;
            /** Format: uri */
            website?: string | null;
        };
        UnreadCounts: {
            /** @description Unread notification count */
            notifications: number;
            /** @description Unread chat mention count */
            chat_mentions: number;
            /** @description Unread direct message count (currently always 0) */
            dms: number;
        };
        ForumMeta: {
            slug: string;
            name: string;
            domain: string;
            description?: string;
        };
        /** @description Portable format for importing/exporting forum data. */
        ExportData: {
            /** @enum {string} */
            forumline_version: "1";
            /** Format: date-time */
            exported_at: string;
            forum: components["schemas"]["ForumMeta"];
            categories?: unknown[];
            profiles?: unknown[];
            threads?: unknown[];
            posts?: unknown[];
            chat_channels?: unknown[];
            chat_messages?: unknown[];
            voice_rooms?: unknown[];
            bookmarks?: unknown[];
            notifications?: unknown[];
            channel_follows?: unknown[];
            notification_preferences?: unknown[];
        };
        /**
         * @description Response for GET /api/livekit. Exactly one of `participants` or `rooms`
         *     is populated depending on whether the `room` query parameter was provided.
         */
        LiveKitParticipantsResponse: {
            /** @description Participants in the requested room (when `room` param provided). */
            participants?: components["schemas"]["LiveKitParticipant"][];
            /** @description All active rooms with participant info (when no `room` param). */
            rooms?: {
                [key: string]: components["schemas"]["LiveKitRoomInfo"];
            };
        };
        LiveKitParticipant: {
            /** @description User ID */
            identity: string;
            /** @description Display name */
            name: string;
        };
        LiveKitRoomInfo: {
            /** @description Number of participants */
            count: number;
            /** @description Display names of participants */
            names: string[];
            /** @description User IDs of participants */
            identities: string[];
        };
        Error: {
            /** @description Human-readable error message */
            error: string;
        };
        Success: {
            /** @example true */
            success?: boolean;
        };
    };
    responses: {
        /** @description Invalid request (missing required fields, malformed body) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication required (missing or invalid session) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                /** @description Seconds to wait before retrying */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Thread UUID */
        ThreadId: string;
        /** @description User UUID */
        UserId: string;
        /** @description Category URL slug */
        CategorySlug: string;
        /** @description Channel URL slug */
        ChannelSlug: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    startLogin: {
        parameters: {
            query?: {
                /** @description URL to redirect to after login completes */
                redirect_uri?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to identity provider */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    authCallback: {
        parameters: {
            query: {
                /** @description Authorization code from the identity provider */
                code: string;
                /** @description CSRF state parameter */
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to forum with session cookie set */
            302: {
                headers: {
                    /** @description Session cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    tokenExchange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description JWT from the embedding Forumline app */
                    token: string;
                };
            };
        };
        responses: {
            /** @description Session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Session token */
                        access_token?: string;
                        /** @description Local forum user ID */
                        local_user_id?: string;
                        user?: components["schemas"]["Profile"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            /** @description Token exchange not supported (forum not embedded) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session (or null if not authenticated) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forum configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForumConfig"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getCategoryBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category URL slug */
                slug: components["parameters"]["CategorySlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of channels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getManifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forum manifest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForumlineManifest"];
                };
            };
        };
    };
    listThreads: {
        parameters: {
            query?: {
                /** @description Maximum number of threads to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of threads with embedded author and category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createThread: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateThreadRequest"];
            };
        };
        responses: {
            /** @description Thread created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description ID of the newly created thread
                         */
                        id?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    getThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Thread UUID */
                id: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thread details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Thread UUID */
                id: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateThreadRequest"];
            };
        };
        responses: {
            /** @description Thread updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    listThreadsByCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category URL slug */
                slug: components["parameters"]["CategorySlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of threads in the category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listUserThreads: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UUID */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of user's threads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    searchThreads: {
        parameters: {
            query: {
                /** @description Search query (matched against thread titles) */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching threads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listPostsByThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Thread UUID */
                id: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of posts with embedded author */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    streamPosts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Thread UUID */
                id: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of new posts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["Post"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            /** @description Post created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description ID of the newly created post
                         */
                        id?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    listUserPosts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UUID */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of user's posts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    searchPosts: {
        parameters: {
            query: {
                /** @description Search query (matched against post content) */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching posts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listChatMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel URL slug */
                slug: components["parameters"]["ChannelSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of chat messages with embedded author */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    sendChatMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel URL slug */
                slug: components["parameters"]["ChannelSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendChatMessageRequest"];
            };
        };
        responses: {
            /** @description Message sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    sendChatMessageByID: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendChatMessageRequest"];
            };
        };
        responses: {
            /** @description Message sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    streamChatMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel URL slug */
                slug: components["parameters"]["ChannelSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of new chat messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ChatMessage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Profile UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    upsertProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Profile UUID (must match authenticated user) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertProfileRequest"];
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    getProfileByUsername: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Username */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getProfilesBatch: {
        parameters: {
            query: {
                /**
                 * @description Comma-separated list of profile UUIDs
                 * @example abc-123,def-456,ghi-789
                 */
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    clearForumlineId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Profile UUID (must match authenticated user) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forumline ID cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listBookmarks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of bookmarks with embedded threads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    addBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description ID of the thread to bookmark
                     */
                    thread_id: string;
                };
            };
        };
        responses: {
            /** @description Bookmark added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    getBookmarkStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Thread UUID */
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmark status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        bookmarked?: boolean;
                        /**
                         * Format: uuid
                         * @description Bookmark ID (only present if bookmarked)
                         */
                        id?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    removeBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Thread UUID */
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmark removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    removeBookmarkById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bookmark UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmark removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listChannelFollows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of followed category IDs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    followChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Category ID to follow
                     */
                    category_id: string;
                };
            };
        };
        responses: {
            /** @description Follow added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        ok?: boolean;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    unfollowChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Category ID to unfollow
                     */
                    category_id: string;
                };
            };
        };
        responses: {
            /** @description Follow removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        ok?: boolean;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    markAllNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All notifications marked as read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listForumlineNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of Forumline-format notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForumlineNotification"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Notification ID to mark as read
                     */
                    id: string;
                };
            };
        };
        responses: {
            /** @description Notification marked as read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getUnreadCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unread counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCounts"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    streamNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ForumlineNotification"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listNotificationPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of notification preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreference"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    updateNotificationPreference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Notification category
                     * @enum {string}
                     */
                    category: "reply" | "mention" | "chat_mention" | "dm" | "new_thread";
                    /** @description Whether notifications for this category are enabled */
                    enabled: boolean;
                };
            };
        };
        responses: {
            /** @description Preference updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        ok?: boolean;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listVoiceRooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of voice rooms */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceRoom"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getLiveKitParticipants: {
        parameters: {
            query?: {
                /** @description Optional room name to filter by */
                room?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Participants data. When `room` is provided, `participants` is populated.
             *     When `room` is omitted, `rooms` is populated.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveKitParticipantsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getLiveKitToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Name of the LiveKit room to join */
                    roomName: string;
                    /** @description Display name for the participant */
                    participantName: string;
                };
            };
        };
        responses: {
            /** @description LiveKit access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description JWT access token for LiveKit */
                        token?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listVoicePresence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of voice presence entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoicePresence"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    setVoicePresence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Slug of the voice room to join */
                    room_slug: string;
                };
            };
        };
        responses: {
            /** @description Presence set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    clearVoicePresence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presence cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    streamVoicePresence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of voice presence changes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["VoicePresence"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Image file (max 5 MB, must have image/* content type)
                     */
                    file: string;
                    /**
                     * @description Storage path override. Must start with `user/{your-id}/` or `thread/`.
                     *     Defaults to `user/{userId}/custom.png`.
                     * @example user/abc-123/custom.png
                     */
                    path?: string;
                };
            };
        };
        responses: {
            /** @description Upload successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uri
                         * @description Public URL of the uploaded image
                         */
                        url?: string;
                    };
                };
            };
            /** @description Invalid file (too large, not an image, or missing) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Invalid upload path */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            429: components["responses"]["RateLimited"];
            /** @description File uploads not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getAdminStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStats"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all user profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    importData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportData"];
            };
        };
        responses: {
            /** @description Import completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        ok?: boolean;
                        forum?: components["schemas"]["ForumMeta"];
                        /** @example import complete */
                        message?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
}
