when:
  - event: push
    branch: main
    path:
      include:
        - "deploy/compose/auth/**"
        - "deploy/secrets.kdbx"
  - event: manual

steps:
  - name: deploy
    image: bash
    environment:
      KEEPASS_PASSWORD:
        from_secret: keepass_password
    commands:
      - ci/deploy.sh auth
